// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBygdFKLt9k51VGulJz8WAHWs9r5U3ZIs0',
    appId: '1:787513510167:web:ff2177eb1f2a60dfd5cf52',
    messagingSenderId: '787513510167',
    projectId: 'cloudcalc-2b19d',
    authDomain: 'cloudcalc-2b19d.firebaseapp.com',
    storageBucket: 'cloudcalc-2b19d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMDkj3y5-12Oat7lhpCpdQwrohD9T0iQw',
    appId: '1:787513510167:android:89190cddfd0ea24cd5cf52',
    messagingSenderId: '787513510167',
    projectId: 'cloudcalc-2b19d',
    storageBucket: 'cloudcalc-2b19d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbc6-rqXWVcMkxYozCK80zCl4t-Qw0mqE',
    appId: '1:787513510167:ios:3ef12ebab312c57bd5cf52',
    messagingSenderId: '787513510167',
    projectId: 'cloudcalc-2b19d',
    storageBucket: 'cloudcalc-2b19d.appspot.com',
    iosClientId: '787513510167-98i63333ed7r4ft86lnf24mk1oiot239.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudCalc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbc6-rqXWVcMkxYozCK80zCl4t-Qw0mqE',
    appId: '1:787513510167:ios:3ef12ebab312c57bd5cf52',
    messagingSenderId: '787513510167',
    projectId: 'cloudcalc-2b19d',
    storageBucket: 'cloudcalc-2b19d.appspot.com',
    iosClientId: '787513510167-98i63333ed7r4ft86lnf24mk1oiot239.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudCalc',
  );
}
